/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React from 'react';
import {Button, StyleSheet, Text, View} from 'react-native';
import ReactNativeSumupsdk from 'react-native-sumupsdk';

const AFFILIATE_API_KEY = 'YOUR_API_KEY';
const ACCESS_TOKEN = 'ACCESS_TOKEN';


export default function App() {

  const pressed = async () => {
    try {
      ReactNativeSumupsdk.test( )
    } catch (error) {
      console.log('ERROR', error);
    }
  };

  const requestPayment = async () => {
    try {
      await ReactNativeSumupsdk.requestPayment({
        ammount: 15.4,
        title: "TITLE test",
      });
    } catch (error) {
      // console.log('ERROR ', error);
      console.log('ERROR login', JSON.stringify(error,null,2));
      await ReactNativeSumupsdk.loginWithToken({accessToken: "9c219d626aaf993927eff83a27d3db3269c2e325701ab20a81933269d10e9fc8"})
      await ReactNativeSumupsdk.requestPayment({
        ammount: 15.4,
        title: "TITLE test",
      });
      

    }
  };

  const login = async () => {
    try {
      const res = await ReactNativeSumupsdk.loginWithToken({accessToken:ACCESS_TOKEN});
      console.log(' login ok ', res);
    } catch (error) {
      console.log('ERROR login', JSON.stringify(error));
    }
  };

  const setup = async () => {
    try {
      const res = await ReactNativeSumupsdk.setupWithKey({affiliateKey: AFFILIATE_API_KEY});
      console.log(' Setup ok ', res);
    } catch (error) {
      console.log('ERROR ', error);
    }
  };

  const setupAndLogin = async () => {
    try {
      const res = await ReactNativeSumupsdk.setupAndLogin({
        affiliateKey: AFFILIATE_API_KEY,
        accessToken: ACCESS_TOKEN,
      }
      );
      console.log(' Setup and login ok ', res);
    } catch (error) {
      console.log('ERROR ', error);
    }
  };
  return (
    <View style={styles.container}>
      <Text style={styles.welcome}>☆ReactNativeSu example☆</Text>
      <Button title="Test" onPress={pressed} />
      <Button title="setup" onPress={setup} />
      <Button title="Login" onPress={login} />
      <Button title="setup and login" onPress={setupAndLogin} />
      <Button title="Request payment" onPress={requestPayment} />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#05FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
