/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Button, Platform, StyleSheet, Text, View } from 'react-native';
import ReactNativeSumupsdk from 'react-native-sumupsdk';

export default class App extends Component {
  state = {
    status: 'starting',
    message: '--'
  };
  async pressed() {
    try {
      
    const returnVal = await ReactNativeSumupsdk.test('keynw dkljnd kljakajs kkj' )
    console.log("SUCCESS",returnVal);
    } catch (error) {
     console.log("ERROR", error); 
    }
    
  }
  render() {
    return (
      <View style={styles.container}>
        <Button title='Test' onPress={this.pressed} />
        <Text style={styles.welcome}>☆ReactNativeSumupsdk example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
